name: CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    # Step 3: Install dependencies and run tests
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    # Step 4: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t your-username/your-app:latest .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
    # Step 1: Checkout the code again
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub (if necessary)
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 3: Push Docker image to local Docker
    - name: Push Docker image
      run: |
        docker tag your-username/your-app:latest localhost/your-app:latest
        docker push localhost/your-app:latest
